import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NextTopLoader from "nextjs-toploader";

const inter = Inter({ subsets: ["latin"] });
import Provider from "@/components/provider";
import { ReactQueryProvider } from "@/components/react-query-provider";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReactQueryProvider>
      <html lang="en">
        <body className={inter.className}>
          <NextTopLoader />
          <Provider>{children}</Provider>
        </body>
      </html>
    </ReactQueryProvider>
  );
}
